name: Continuous desintegration 2
on:
  issues:

permissions: {}

jobs:
  jammy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "Body of issue is ${{ github.event.issue.title }}"
  
  noble:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FLAG_UBUCTF: ${{ secrets.FLAG_UBUCTF2 }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Log PR created executions
        run: |
          bash test.sh "$FLAG_UBUCTF"
