name: Basic PR analysis
on:
  pull_request:

permissions: {}

jobs:
  focal:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      id-token: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Execute checks on PR
        run: |
          echo "TBD"
